core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('products/',
         views.ProductListView.as_view(),
         name='product_list'),
    path('products/<int:pk>/',
         views.ProductDetailView.as_view(),
         name='product_detail'),
    path('categories/',
         views.CategoryListView.as_view(),
         name='category_list'),
    path('categories/<int:pk>/',
         views.CategoryDetailView.as_view(),
         name='category_detail'),
    path('clients/',
         views.ClientListView.as_view(),
         name='client_list'),
    path('clients/<int:pk>/',
         views.ClientDetailView.as_view(),
         name='client_detail'),
    path('orders/',
         views.OrderListView.as_view(),
         name='order_list'),
    path('orders/<int:pk>/',
         views.OrderDetailView.as_view(),
         name='order_detail'),
    path('products/create/',
         views.ProductCreateView.as_view(),
         name='product_create'),
    path('products/update/<int:pk>/',
         views.ProductUpdateView.as_view(),
         name='product_update'),
    path('products/delete/<int:pk>/',
         views.ProductDeleteView.as_view(),
         name='product_delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]

core/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Client(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Order(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    date = models.DateTimeField()
    product = models.ManyToManyField(Product)

core/forms.py
from django import forms


class ProductSearchForm(forms.Form):
    search_query = forms.CharField(label='Поиск', max_length=100)

core/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from core import models
from django.views.generic.edit import CreateView,\
    UpdateView, DeleteView, FormView
from core.forms import ProductSearchForm
from django.urls import reverse_lazy
from django.db.models import Q


# Create your views here.


def product_list(request):
    products = models.Product.objects.all()
    return render(request, 'core/product_list.html', {'products': products})


def product_detail(request, pk):
    product = get_object_or_404(models.Product, pk=pk)
    return render(request, 'core/product_detail.html', {'product': product})


def category_list(request):
    categories = models.ProductCategory.objects.all()
    return render(request, 'core/category_list.html',
                  {'categories': categories})


def category_detail(request, pk):
    category = get_object_or_404(models.ProductCategory, pk=pk)
    return render(request, 'core/category_detail.html', {'category': category})


def client_list(request):
    clients = models.Client.objects.all()
    return render(request, 'core/client_list.html', {'clients': clients})


def client_detail(request, pk):
    client = get_object_or_404(models.Client, pk=pk)
    return render(request, 'core/client_detail.html', {'client': client})


def order_list(request):
    orders = models.Order.objects.all()
    return render(request, 'core/order_list.html', {'orders': orders})


def order_detail(request, pk):
    order = get_object_or_404(models.Order, pk=pk)
    return render(request, 'core/order_detail.html', {'order': order})


class ProductDetailView(DetailView):
    model = models.Product
    template_name = 'core/product_detail.html'
    context_object_name = 'product'


class CategoryListView(ListView):
    model = models.ProductCategory
    template_name = 'core/category_list.html'
    context_object_name = 'categories'


class CategoryDetailView(DetailView):
    model = models.ProductCategory
    template_name = 'core/category_detail.html'
    context_object_name = 'category'


class ClientListView(ListView):
    model = models.Client
    template_name = 'core/client_list.html'
    context_object_name = 'clients'


class ClientDetailView(DetailView):
    model = models.Client
    template_name = 'core/client_detail.html'
    context_object_name = 'client'


class OrderListView(ListView):
    model = models.Order
    template_name = 'core/order_list.html'
    context_object_name = 'orders'


class OrderDetailView(DetailView):
    model = models.Order
    template_name = 'core/order_detail.html'
    context_object_name = 'order'


class ProductCreateView(CreateView):
    model = models.Product
    fields = ['name', 'description', 'price', 'category']
    template_name = 'core/product_form.html'
    success_url = reverse_lazy('core:product_list')


class ProductUpdateView(UpdateView):
    model = models.Product
    fields = ['name', 'description', 'price', 'category']
    template_name = 'core/product_update.html'
    success_url = reverse_lazy('core:product_list')


class ProductDeleteView(DeleteView):
    model = models.Product
    template_name = 'core/product_confirm_delete.html'
    success_url = reverse_lazy('core:product_list')


class ProductListView(FormView):
    template_name = 'core/product_list.html'
    form_class = ProductSearchForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = models.Product.objects.all()
        search_query = self.request.GET.get('search_query')

        if search_query:
            products = products.filter(Q(name__icontains=search_query))

        context['products'] = products
        return context

core/templates/core/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}HW8{% endblock %}</title>
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'core:category_list' %}">Категории товаров</a></li>
            <li><a href="{% url 'core:product_list' %}">Товары</a></li>
            <li><a href="{% url 'core:client_list' %}">Клиенты</a></li>
            <li><a href="{% url 'core:order_list' %}">Заказы</a></li>

        </ul>
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

core/templates/core/category_detail.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>{{ category.name }}</h1>
    <p>{{ category.description }}</p>
{% endblock %}

core/templates/core/category_list.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>Категории товаров</h1>
    <ul>
        {% for category in categories %}
            <li><a href="{% url 'core:category_detail' pk=category.pk %}">{{ category.name }}</a></li>
        {% empty %}
            <li>Нет доступных категорий.</li>
        {% endfor %}
    </ul>
{% endblock %}

core/templates/core/client_detail.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>{{ client.name }}</h1>
    <p>Email: {{ client.email }}</p>
    <p>Телефон: {{ client.phone }}</p>
{% endblock %}

core/templates/core/client_list.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>Клиенты</h1>
    <ul>
        {% for client in clients %}
            <li><a href="{% url 'core:client_detail' pk=client.pk %}">{{ client.name }}</a></li>
        {% empty %}
            <li>Клиенты отсутствуют.</li>
        {% endfor %}
    </ul>
{% endblock %}

core/templates/core/order_detail.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>Заказ для {{ order.client }}</h1>
    <p>Дата: {{ order.date }}</p>
    <p>Товар:</p>
    <ul>
        {% for product in order.product.all %}
            <li>{{ product.name }} - {{ product.price }}₽</li>
        {% empty %}
            <li>В этом заказе товаров не найдено.</li>
        {% endfor %}
    </ul>
{% endblock %}

core/templates/core/order_list.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>Заказы</h1>
    <ul>
        {% for order in orders %}
            <li><a href="{% url 'core:order_detail' pk=order.pk %}">{{ order.date }}</a></li>
        {% empty %}
            <li>Заказы не найдены.</li>
        {% endfor %}
    </ul>
{% endblock %}

core/templates/core/product_confirm_delete.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>Удалить товар "{{ object.name }}"?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Удалить</button>
        <a href="{% url 'core:product_list' %}">Отмена</a>
    </form>
{% endblock %}

core/templates/core/product_detail.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>{{ product.name }}</h1>
    <p>{{ product.description }}</p>
    <p>Цена: {{ product.price }}₽</p>
    <p>Категория товара: {{ product.category }}</p>
{% endblock %}

core/templates/core/product_form.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>Добавить товар</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

core/templates/core/product_list.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>Товары</h1>
    <form method="GET" action="">
        {{ form.as_p }}
        <button type="submit">Поиск</button>
    </form>
    <ul>
        {% for product in products %}
            <li><a href="{% url 'core:product_detail' pk=product.pk %}">{{ product.name }}</a></li>
        {% empty %}
            <li>Товары не найдены.</li>
        {% endfor %}
    </ul>
{% endblock %}

core/templates/core/product_update.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>Изменить товар</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}